server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: supplier-onboarding-service-route
          # The URI must match the service name registered with Eureka
          uri: lb://supplier-onboarding-service
          predicates:
            - Path=/api/auth/**, /api/v1/suppliers/**
