server:
  port: 8081

# Custom application properties are cleaner when grouped under a non-spring prefix
app:
  security:
    jwt:
      secret-key: shjsfhdsjdkjfhsifoiewuroiwuru=
      expiration: 86400000 # 24 hours in milliseconds

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/supplier_db
    username: admin
    password: password # For production, use environment variables or a vault
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Caution: Use 'validate' or 'none' in production
    properties:
      hibernate:
        default_schema: suppliers
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
